export const mockExercises = [
  {
    id: 1,
    name: 'Bench Press',
    nameFr: 'Développé couché',
    muscleGroup: 'chest',
    secondaryMuscles: ['triceps', 'front_delts'],
    difficulty: 'intermediate',
    equipment: 'barbell',
    defaultSets: 3,
    defaultReps: '8-12',
    defaultRestSeconds: 90,
    caloriesPerMinute: 8.5,
    formCues: ['Keep feet flat', 'Retract shoulder blades', 'Lower to mid-chest', 'Drive through heels'],
    formCuesFr: ['Gardez les pieds plats', 'Rentrez les omoplates', 'Descendez au milieu des pectoraux', 'Poussez par les talons'],
    posterImage: '/exercises/bench-press.jpg',
    videoMp4: null,
    isFavorite: true,
    usageCount: 47
  },
  {
    id: 2,
    name: 'Squat',
    nameFr: 'Squat',
    muscleGroup: 'quadriceps',
    secondaryMuscles: ['glutes', 'hamstrings', 'core'],
    difficulty: 'intermediate',
    equipment: 'barbell',
    defaultSets: 3,
    defaultReps: '8-12',
    defaultRestSeconds: 90,
    caloriesPerMinute: 9.0,
    formCues: ['Chest up', 'Drive through heels', 'Go below parallel if mobility allows'],
    formCuesFr: ['Poitrine sortie', 'Poussez sur les talons', 'Descendez sous la parallèle si possible'],
    posterImage: '/exercises/squat.jpg',
    videoMp4: null,
    isFavorite: false,
    usageCount: 22
  },
  {
    id: 3,
    name: 'Pull-up',
    nameFr: 'Traction',
    muscleGroup: 'back',
    secondaryMuscles: ['biceps', 'core'],
    difficulty: 'advanced',
    equipment: 'bodyweight',
    defaultSets: 3,
    defaultReps: '5-10',
    defaultRestSeconds: 90,
    caloriesPerMinute: 8.0,
    formCues: ['Full extension at bottom', 'Pull chest to bar'],
    formCuesFr: ['Extension complète en bas', 'Tirez la poitrine vers la barre'],
    posterImage: '/exercises/pullup.jpg',
    videoMp4: null,
    isFavorite: true,
    usageCount: 50
  },
  {
    id: 4,
    name: 'Overhead Press',
    nameFr: 'Développé Militaire',
    muscleGroup: 'shoulders',
    secondaryMuscles: ['triceps', 'core'],
    difficulty: 'intermediate',
    equipment: 'barbell',
    defaultSets: 3,
    defaultReps: '8-12',
    defaultRestSeconds: 90,
    caloriesPerMinute: 7.5,
    formCues: ['Core tight', 'Don\'t overextend lower back'],
    formCuesFr: ['Gainez', 'Ne cambrez pas trop le bas du dos'],
    posterImage: '/exercises/ohp.jpg',
    videoMp4: null,
    isFavorite: false,
    usageCount: 15
  },
  {
    id: 5,
    name: 'Dumbbell Curl',
    nameFr: 'Curl Biceps Haltères',
    muscleGroup: 'biceps',
    secondaryMuscles: [],
    difficulty: 'beginner',
    equipment: 'dumbbell',
    defaultSets: 3,
    defaultReps: '10-15',
    defaultRestSeconds: 60,
    caloriesPerMinute: 5.0,
    formCues: ['Keep elbows pinned', 'Squeeze at the top'],
    formCuesFr: ['Coudes collés au corps', 'Contractez en haut'],
    posterImage: '/exercises/db-curl.jpg',
    videoMp4: null,
    isFavorite: true,
    usageCount: 65
  }
];
